# Cosas importantes por recordar

Configurar presición de big float:

In [9]:
setprecision(BigFloat, 1000)
BigFloat("1.3430000000000000000000000000000000000000000000000000000000000000000000000000000000000003")

1.34300000000000000000000000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009

## Vectores y matrices

Hay tres formas de crear vectores:

In [5]:
v = collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [3]:
w = [1,2,3,4,5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [10]:
u = [1 2 3 4 5]

1×5 Array{Int64,2}:
 1  2  3  4  5

## Cómo funciona el push! y el append! para hacer crecer vectores

In [1]:
?push!

search: push! pushfirst! pushdisplay



```
push!(collection, items...) -> collection
```

Insert one or more `items` at the end of `collection`.

# Examples

```jldoctest
julia> push!([1, 2, 3], 4, 5, 6)
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
```

Use [`append!`](@ref) to add all the elements of another collection to `collection`. The result of the preceding example is equivalent to `append!([1, 2, 3], [4, 5, 6])`.


In [4]:
push!(w,6,7,8)

8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8

In [6]:
append!(w,v)

13-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 1
 2
 3
 4
 5

También se pueden hacer matrices haciendo listas horizontales de listas verticales:

In [11]:
A = [3v 2v 4v 1v 5v]

5×5 Array{Int64,2}:
  3   2   4  1   5
  6   4   8  2  10
  9   6  12  3  15
 12   8  16  4  20
 15  10  20  5  25

Ubicar elementos de la matriz:

In [16]:
A[3,4]

3

Sin embargo, no se pueden hacer matrices de listas verticales de listas horizontales

In [19]:
B = [3u, 2u, 4u,u,5u]

5-element Array{Array{Int64,2},1}:
 [3 6 … 12 15] 
 [2 4 … 8 10]  
 [4 8 … 16 20] 
 [1 2 … 4 5]   
 [5 10 … 20 25]

Para acceder a un elemento de una lista, vasta nombrar la lista, abrir un corchete y poner el índice de elemento que se quiere acceder

In [20]:
B[1][4]

12

Método cool para obtener todos los elementos de una columna o un reenglón

In [22]:
A[3,:]

5-element Array{Int64,1}:
  9
  6
 12
  3
 15

## Operaciones

Es importante esta parte, ya que nos indica cómo utilizar y diferenciar el producto punto y el producto entrada a entrada

In [24]:
using LinearAlgebra
a = [2,3,5.33] 
b = [-1.2,3.3,1.33]
a⋅b, a×b, norm(a), a.*b, a.^3, length(A)

(14.588899999999999, [-13.599, -9.056, 10.2], 6.434974747425199, [-2.4, 9.9, 7.0889], [8.0, 27.0, 151.419], 25)

Notemos que tanto el producto "*", como la potencia "^", para el caso de listas, se requiere usar un punto antes de la operación. Esto significa que se aplicará esa operación a todos los elementos de la lista. Esto es general: 


In [25]:
sin.(a)

3-element Array{Float64,1}:
  0.9092974268256817
  0.1411200080598672
 -0.8152642144499634

In [26]:
A = rand(3,3)
A*b, A*A, inv(A), transpose(A), size(A)

([0.960356, 2.66336, 1.66745], [1.26941 0.760793 1.16254; 0.771083 0.768257 0.838754; 1.1139 0.808156 1.59853], [0.427654 -1.15041 0.871555; -1.4472 1.21326 0.874677; 1.01913 0.587681 -0.728019], [0.626627 0.0727315 0.935905; 0.145894 0.537949 0.638483; 0.925456 0.733389 0.513939], (3, 3))

## Existen algunas otras operaciones sobre listas que no son matemáticas, como agregar un elemento a una lista o quitarlo: 

In [28]:
push!(a,6)
a

5-element Array{Float64,1}:
  2.0 
  3.0 
  5.33
 12.2 
  6.0 

In [31]:
pop!(a)
a

4-element Array{Float64,1}:
 2.0 
 3.0 
 8.0 
 5.33

In [32]:
insert!(a,3,20.)
a

5-element Array{Float64,1}:
  2.0 
  3.0 
 20.0 
  8.0 
  5.33

In [33]:
deleteat!(a,2)

4-element Array{Float64,1}:
  2.0 
 20.0 
  8.0 
  5.33

Observemos que en todas estas operaciones (funciones) tenemos que terminan con un signo de interrogación, esto provoca que se reescriba la variable con la que estamos trabajando

## Para incertar variables dentro de un texto se puede usar el símbolo $: 

In [35]:
nombre = "Bee"
a = "hola $(nombre), cómo te va?"

"hola Bee, cómo te va?"

## Una forma de definir conjuntos:

In [36]:
X = [x^2-x+1 for x in 0.3:0.01:.8]

51-element Array{Float64,1}:
 0.79              
 0.7861            
 0.7824            
 0.7788999999999999
 0.7756000000000001
 0.7725            
 0.7696000000000001
 0.7669            
 0.7644            
 0.7621            
 0.76              
 0.7581            
 0.7564            
 ⋮                 
 0.7861            
 0.79              
 0.7941            
 0.7984            
 0.8029            
 0.8076            
 0.8125            
 0.8176            
 0.8229            
 0.8284            
 0.8341000000000001
 0.8400000000000001

# Funciones

En general podemos definir funciones como lo hacemos en cálculo, poniendo el nombre de la función, seguido de paréntecis que dentro tienen los argumentos que se evaluarán, después un signo de igual y seguido de eso las instrucciones sobre cómo operar la función. Por ejemplo:

In [37]:
Area_circulo(r) = π*r^2
Area_circulo(2)

12.566370614359172

Sin embargo, hay algunas funciones lo suficientemente complejas que utilizan condicionales y ciclos para definirse. Estas funciones se pueden definir utilizando la palabra function:

In [41]:
function Saludo(nombre, hora)
    a = :string
    if hora<12
        a = "buenos días, $(nombre), ¿cómo te va?"
    elseif 12<=hora<18
        a = "buenas tardes, $(nombre), ¿cómo te va?"
        return "estoy ocupado"
    else
        a = "buenas noches, $(nombre), ¿cómo te va?"
    end
    for i in 1:2
        
    end
    a
end

Saludo("Ata",36)

"buenas noches, Ata, ¿cómo te va?"

In [56]:
function BabylonianRoot(y :: Real)
    x = 2
    for i in 1:3
        x = 0.5(x+y/x)
    end
    return x
end

BabylonianRoot(2)
    

1.4142156862745097

$\phi$